### ISSUE TITLE
Use photon.komoot.io geocoding API instead of built in city list

### ISSUE THREAD

**Issue by woheller69** [woheller69/weather#12]
for easier searching, as city list does not allow search based on ZIP codes

**Comment by woheller69** [comment]
this will also translate city names #2

**Comment by kojid0** [comment]
Just tested the app in photon branch.
Searching for city names will bring up a lot of places now, quite overwhelming. Also, searching for zip codes brings cities all over the world. But it works, yay!
As far as I have tested it, photon looks quite promising, but the way of displaying things isn't as user friendly as it should be: 

- Order: Sometimes when searching for zip codes, irrelevant places come first, then zip code. Example: "64048"
- Results without a city name have "," at the beginning. Example: "64048"
- Results may be displayed several times, just with different coordinates (nobody will surely know the difference, hence think about removing coordinates from the list and bring the center of the city as the only result

![debug](https://user-images.githubusercontent.com/24477557/112204267-c1493600-8c13-11eb-9abd-16cc092d3f1a.png)


Another thing that came into my mind: the app displays a map with a pin - why not let the user set the pin on the map directly (as an option)? Feel free to open a new issue if you want to further discuss this.

**Comment by woheller69** [comment]
I am also quite enthusiastic.The result list is just the unsorted stream that is coming in. But as you type results are getting better.

Good idea to remove the "," where not needed and the coordinates

**Comment by woheller69** [comment]
...done. Ready for testing

**Comment by kojid0** [comment]
Looks good to me!
What about showing the difference between internal city list and Photon API? Maybe "internal city list (no zip codes)" / "Photon API (with zip codes)"?
Alternatively, a pop-up could be displayed when a user wants to add a new city starting with a number (hence search via zip code).

**Comment by woheller69** [comment]
Included in V3.0
