### ISSUE TITLE
Widget malformed

### ISSUE THREAD

**Issue by kojid0** [woheller69/weather#13]
The widget looks a little malformed over here. Temperature and Sunrise/Sunset are a little in the weather-icon. More important, UV-index and Rain Prediction (I guess it's this, I haven't really figured it out yet) are at the same spot. Smaller font and smaller boxes would solve this issue.

![image](https://user-images.githubusercontent.com/24477557/111916870-5534c980-8a7d-11eb-825b-dbb441883da7.png)

----
 - App version: 2.0 (F-Droid)
 - Android version: 11
 - Device: Google Pixel 5

**Comment by woheller69** [comment]
just click on it and resize it as needed

**Comment by kojid0** [comment]
> just click on it and resize it as needed

Should't the size of the widget set the font/box size automatically? The larger the widget, the larger the font. The smaller the widget, the smaller the font, so that everything fits on it.

**Comment by woheller69** [comment]
no, Android does not automatically scale fonts based on widget size. I haven't seen this in other weather apps either.
That is why the widget is resizable. If someone creates a pull request with a convincing better solution I will of course reconsider it...
