### ISSUE TITLE
Feature Request: New widget design

### ISSUE THREAD

**Issue by kojid0** [woheller69/weather#14]
I'd really appreciate to have the current time integrated in the widget, combined with a weather forecast.
As an idea:

![image](https://user-images.githubusercontent.com/24477557/111917042-2ec35e00-8a7e-11eb-953a-4d11f1d7bc92.png)

**Comment by woheller69** [comment]
not planned right now, but additional widgets might be added in future

**Comment by kojid0** [comment]
Thanks.
I have a better suggestion: Integrate the diagram, if possible:

Quick mockup:
![image](https://user-images.githubusercontent.com/24477557/111918452-671a6a80-8a85-11eb-9900-6202756c060f.png)

**Comment by peter-czy** [comment]
> Quick mockup:

This looks quite ugly... Diagram is one of the best parts of RadarWeather, but don't show it that way. I'd go with diagram + small weather icons below each day

**Comment by kojid0** [comment]
I know, it was just a very quick draft.
I like the idea of icons below days and also looked in other apps like WetterOnline, Weather.com and Meteogram how they do diagrams and widgets.
I've created a new mockup, this time with higher quality.
![Diagramm2](https://user-images.githubusercontent.com/24477557/112199146-26019200-8c0e-11eb-8a7b-cad6f12bd947.png)

**Comment by woheller69** [comment]
New 5day widget coming in V3.3. Chart unfortunately not possible with the Williamchart library which is currently being used.
