### ISSUE TITLE
Feature Request: Round Temperatures

### ISSUE THREAD

**Issue by kojid0** [woheller69/weather#15]
While some might prefer to see exact temperatures, it is mostly enough to see them rounded by .0 or .5 
(e.g. 12,8°C --> 13°C or 12,4°C --> 12,5°C). I personally don't need decimals at all (12,5°C--> 13°C).

It will be easier to read them fast.

**Comment by woheller69** [comment]
I know. But making number of digits adjustable is not so easy and if I generally remove the digit  others will complain...

**Comment by peter-czy** [comment]
OpenWeather (from https://openweathermap.org/) shows them rounded and has a page for unit-settings. Maybe that is a solution for everyone, if technically possible?
Privacyfriendlyweather has both
![image](https://user-images.githubusercontent.com/81222469/112158317-55050d00-8be8-11eb-91a1-7cb97d800f18.png)
Maybe we can see how they solved the problem

**Comment by kojid0** [comment]
@peter-czy Just checked the app and I cannot see the city list as pictured in the right-hand picture. It seems to be a playstore preview but not in the app (anymore?).

**Comment by kojid0** [comment]
Rounding is actually pretty simple via `Math.round()` but I spent 2 hours trying to remove the decimals, but it keeps showing `5.0` instead of `5`
Even converting to `int` (cannot contain a decimal per definition) doesn't help. It must be something else but I'm unable to figure it out. 
@woheller69, I know you don't want to fix this issue, but do you have an idea and can you give me a hint?

**Comment by woheller69** [comment]
https://github.com/woheller69/weather/blob/main/app/src/main/java/org/woheller69/weather/ui/Help/StringFormatUtils.java

done with decimalFormat

**Comment by kojid0** [comment]
> done with decimalFormat

got it, thanks. Tested it a little and seems to work fine on my phone.

> if I generally remove the digit others will complain...

I think that very few people need a very exact temperature. Besides, it is questionable whether the calculated temperature really corresponds to the real temperature. It may be that the current temperature (right now) matches with one decimal place, but it is hardly possible to calculate the temperatures with high probability for the next hours or days to one decimal place.

Hence, the current representation with decimal places is actually probably incorrect with high probability (e.g. for the daily maximum temperature in three days) and makes things unnecessarily complex, so that you have to think shortly every time. Even openweathermaps itself round its data (in openweather app), just like other "big companies" do.

I'm fine creating a private fork of you app but if you reconsider your decision, I'm happy to propose a PR. Your app - your decision :-)

**Comment by woheller69** [comment]
I'll think about it. What about a PR including a setting to switch the decimal on / off?
But first I would like to finalize that photon search stuff...

**Comment by kojid0** [comment]
> I'll think about it. 

Alright

> What about a PR including a setting to switch the decimal on / off?

Would ne nice, indeed, but this is actually difficult to solve. I'm not a good programmer (only basic Java skills) so I can't do this. :-/ I already tried to play with a setting for bft - m/s - km/h - mph but I couldn't even do this.

> But first I would like to finalize that photon search stuff...

Sure, I'm exited!

**Comment by woheller69** [comment]
9 months ago I did not have a clue about Java. Now I know at least a little...

**Comment by woheller69** [comment]
I looked a little into it. It is at least not as simple as just changing one decimalFormat.
Otherwise e.g. precipitation is also rounded, and that is not acceptable...

**Comment by kojid0** [comment]
> I looked a little into it. It is at least not as simple as just changing one decimalFormat.
> Otherwise e.g. precipitation is also rounded, and that is not acceptable...

I have also tried the last past days but I didn't get it work correctly. Maybe someone else is able to do this in future. But thanks for trying! I appreciate it :-)

**Comment by woheller69** [comment]
@kojid0 please test the feature in photon branch

**Comment by kojid0** [comment]
> @kojid0 please test the feature in photon branch

Works perfectly! No bugs found. Hope your app gets more attention - it's getting better and better.
I'll close this now.

**Comment by woheller69** [comment]
Radius search was missing. Fixed that as well
