### ISSUE TITLE
WANTED: Beta Testers

### ISSUE THREAD

**Issue by woheller69** [woheller69/weather#16]
I am currently adding a new online city search via the photon API (photon.komoot.io).
Would be good to have some people testing this feature.
See branch photon. I will provide an apk in a few days, but if you can build on your own you can start already.
There is a new option in settings to switch between city list and photon

**Comment by kojid0** [comment]
Nice work, I left my feedback here https://github.com/woheller69/weather/issues/12#issuecomment-805162190
