### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Stenafo** [woheller69/weather#19]
Hi, I wanted to know if I can somehow help translate the application.
Have a good day :)

**Comment by woheller69** [comment]
Sure, which language(s) would you like to add?
We need a translation of strings.xml and another folder in fastlane with description, etc for F-Droid

**Comment by Stenafo** [comment]
I translate into Italian, I'm almost done :)

**Comment by Stenafo** [comment]
I don't know how to translate "shower rain" and "shower snow" :(

**Comment by woheller69** [comment]
translate.google.com says

doccia a pioggia

doccia di neve

does it make sense?

**Comment by Stenafo** [comment]
I thought of translating it like this but it doesn't make any sense.  could you explain to me what it means?  so I can find the right words

**Comment by woheller69** [comment]
thats what all the online translators say...

shower rain is a short strong rain
If you are outside without an umbrella you do not need to take a shower anymore afterwards

**Comment by Stenafo** [comment]
I finished the translation, do you want me to put everything on pastebin and send you the link?

**Comment by woheller69** [comment]
Ideally you push it to your forked Github repository and create a pull request

**Comment by woheller69** [comment]
will be included in V3.2
