### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by rikishi0071** [woheller69/weather#2]
Hello! Your app is amazing because it has not only 3h/5d but has daily (8d) weather display feature which is not implemented in Forecastie! Can I translate it to Russian?

**Comment by woheller69** [comment]
I have removed a lot of languages when I forked it from Privacy Friendly Weather to keep it simple as long as I make significant changes. I would suggest to wait for a month or so while I am cleaning up some stuff and fix some minor bugs.
But then I have no objections if you create a pull request with Russian translation.

**Comment by woheller69** [comment]
When translating: please also translate the descriptions in fastlane directory. Then it will appear in Russian also in F-Droid

**Comment by rikishi0071** [comment]
I've created a RP with Russian translation changes. I've translated both strings.xml and description (title, short_description and full_description) for F-Droid repository.
Look at: https://github.com/woheller69/weather/pull/4

**Comment by woheller69** [comment]
Thanks. I integrated it. If you can compile on your own you can already try. Otherwise it should be in next version V1.4

**Comment by rikishi0071** [comment]
Thank you! I'll be waiting for the next F-Droid release. By the way, is there any way to translate city names, which are taken from OpenWeatherMap API in "Manage locations" tab and abbreviations such as "rh", "hPa", "Bft" and so on?

**Comment by woheller69** [comment]
For the cities that is not possible. For the units it might be possible using string resources

**Comment by woheller69** [comment]
I added resources for:
%rh
Bft
hPa
☔ 60 min:

How should they be translated?

**Comment by woheller69** [comment]
also added "mm" and "km"
Please check latest strings.xml in values-ru and let me know if that is ok

**Comment by rikishi0071** [comment]
%отн. вл.
по Бофорту
гПа
60 мин.
мм
км

Here are the translations. Thank you

**Comment by woheller69** [comment]
Can the 2 first be shortened?  Otherwise all elements will be much wider and you will maybe only see forecasts for 2 hours at the same time

**Comment by rikishi0071** [comment]
%вл.
Бфт

**Comment by woheller69** [comment]
Ok great. Will add that.

**Comment by woheller69** [comment]
Release is on its way through F-Droid. Will take a few days. Please let me know when everything is ok.

**Comment by woheller69** [comment]
Available on F-Droid now

**Comment by woheller69** [comment]
@rikishi0071 there is a pull request with some changes to russian translation. Would you like to review it?

**Comment by woheller69** [comment]
using the built in editor names in the city list can now also be modified to cyrillic alphabet
