### ISSUE TITLE
Feature request: Gadgetbridge API support

### ISSUE THREAD

**Issue by roshavagarga** [woheller69/weather#21]
Hello,

Close this if you feel like it's an unreasonable request, but I'd love it if I could share the weather data from this app to Gadgetbridge.

They currently support 2 F-droid sources as seen [here](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Weather).

An example of how one of those handled serving the info via the Gadgetbridge API can be found [here](https://codeberg.org/Starfish/TinyWeatherForecastGermany/src/branch/master/app/src/main/java/de/kaffeemitkoffein/tinyweatherforecastgermany/GadgetbridgeAPI.java).

**Comment by woheller69** [comment]
Why don't you use the weather notifications app (no 2 in the F-Droid list) as weather provider? It uses the same source of weather data from OpenWeatherMap.

**Comment by roshavagarga** [comment]
Mainly because I prefer having a standalone app, for when I'm not wearing my smartband, but have my phone on me and yours is the one I liked the most out of the ones available in F-Droid.

**Comment by woheller69** [comment]
So if I understand this right there should be a switch in settings and when switched on RadarWeather should provide the weather data for e.g. a smart watch. Just for the first city or for all?
I don't have such gadgets, so I won't be able to implement and test this.  But maybe someone else wants to develop and test this feature and create a pull request? As long as it does not impact normal app behaviour I might merge it

**Comment by roshavagarga** [comment]
Since RadarWeather allows having more than one city, it'd be best to default to the first one, as long as they can be rearranged. Either that or a 'favorite' button?
I'm happy that you're open to the idea should there be a pull request :)

Examples for the java segments that pick up the sent data in Gadgetbridge can be found [here](https://codeberg.org/Freeyourgadget/Gadgetbridge/src/branch/master/app/src/main/java/ru/gelin/android/weather/notification/ParcelableWeather2.java) and [here](https://codeberg.org/Freeyourgadget/Gadgetbridge/src/branch/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/TinyWeatherForecastGermanyReceiver.java).

**Comment by woheller69** [comment]
I would use the first city because my widget is handled in the same way. If the user wants to change he can rearrange cities. Then the only visible difference in the app would be a switch in settings to activate/deactivate this feature. Default setting: OFF.

**Comment by roshavagarga** [comment]
Yeah, I agree that following what you're used to is the best and this should definitely be set as OFF by default, since most people will not use Gadgetbridge :+1:

**Comment by woheller69** [comment]
Ideally it should be implemented like possiblyUpdateWidgets(...) in my code which is called when new data is received from OpenWeatherMap

    possiblyUpdateWidgets(...);
    possiblyUpdateGadgetBridge(...);

**Comment by woheller69** [comment]
Obviously nobody wants to implement that at the moment. We can reopen any time if needed
