### ISSUE TITLE
Beaufort scale

### ISSUE THREAD

**Issue by Stenafo** [woheller69/weather#25]
The Beaufort scale is not commonly used (at least in Italy), it would be possible to choose from the settings whether to use that or the classic measurement in km/h?
:)

**Comment by woheller69** [comment]
see #9

**Comment by woheller69** [comment]
I added an option to switch Beaufort scale off. Then km/h or mph will be used

**Comment by Stenafo** [comment]
Wow, thanks a lot! :)
