### ISSUE TITLE
Negative amount of rain

### ISSUE THREAD

**Issue by gappleto97** [woheller69/weather#28]
Hi,

Not sure if this is a post processing bug on your end, or a bug on OpenWeatherMaps' part, but the app currently says I should expect negative rain during one of the hour slices

![](https://i.imgur.com/REPy5Ra.jpg)

**Comment by woheller69** [comment]
I think that is a bug on OpenWeatherMap side. Which Waverly is it?

**Comment by woheller69** [comment]
Found it. The problem occurs at the point where we are switching from 1h intervals to 3h intervals. There I am subtracting values for times that have been reported in 1h slices already. If their 1h and 3h values are not consistent negative values could be shown. Will have a look at it and see if I can improve
