### ISSUE TITLE
widget support

### ISSUE THREAD

**Issue by Happyfeet01** [woheller69/weather#3]
Nice App. Is it possible to add an widget ?

**Comment by woheller69** [comment]
Not planned at the moment. I removed the widgets from the original app as they were not working properly.
But maybe in future...

**Comment by woheller69** [comment]
Planned for next release V2.0:

<img src="https://raw.githubusercontent.com/woheller69/weather/main/app/src/main/res/drawable-nodpi/weather_widget_preview.png" >

**Comment by woheller69** [comment]
V2.0 released. Should be on F-Droid in a few days
