### ISSUE TITLE
Dark mode App/widget

### ISSUE THREAD

**Issue by Depudee** [woheller69/weather#30]
If I set in the settings no dark mode and I go back in the App there is no dark mode. If I close the App and open it, then the App is in dark mode, although the setting is no dark mode. The widget is always dark. Is that normal?

 - App version: 4.3
 - Android version: 11
 - Device: Pixel 3a

**Comment by woheller69** [comment]
the widget always follows your system dark mode.

In the app dark mode should go away (when switched off) as soon as you change activity, e.g. switch from settings to weather

**Comment by Depudee** [comment]
"In the app dark mode should go away (when switched off) as soon as you change activity, e.g. switch from settings to weather"

Correct. But when the app starts, on my device it is dark and in settings dark mode is switched off . On start it should than be in normal mode, if dark mode is switched off I think.

**Comment by woheller69** [comment]
I think I now see what you mean. When the system is in dark mode but in the app dark mode is switched off the app nevertheless starts in dark mode and only switches off when Activity is changed. At next start dark mode is used again as long as the system is in dark mode. Should be fixed in next release

**Comment by jwsp1** [comment]
> the widget always follows your system dark mode.

Any chance this can be fixed? I like dark mode for my system but the weather widget doesn't look nice in dark mode.

**Comment by woheller69** [comment]
you can switch it off in settings. Then app and widget do not use dark mode.
Why does the widget not look nice in dark mode? Too dark?

**Comment by jwsp1** [comment]
> you can switch it off in settings. Then app and widget do not use dark mode. 

Unfortunately, this doesn't work for me. Although the switch is turned off (app is in light mode), the widget is always in dark mode, even when removing and creating again.

> Why does the widget not look nice in dark mode? Too dark?

Yes, it is too dark in my opinion. I'd make the black background transparent (maybe only 70% black, 30% transparency). Also, dark grey text on a black background doesn't look nice --> I'd prefer white text for better readability.

**Comment by woheller69** [comment]
I made dark night colors a bit lighter and the widget slightly transparent

**Comment by jwsp1** [comment]
Thank you!

**Comment by jwsp1** [comment]
F-Droid updated your app and the black widget background was made more transparent👍🏼 I'd still say that I prefer day theme on the app and the widget. Can you link light app theme to light widget and dark app theme to dark widget?

**Comment by woheller69** [comment]
I did not specify using dark mode for the widget. That seems to be done automatically by the operating system

**Comment by jwsp1** [comment]
Okay 😔 thought it can be specified since other apps are also capable of doing this. [Etar](https://f-droid.org/en/packages/ws.xsoh.etar/)  sets the app and widget design to bright/dark, according to the app settings, not device settings
