### ISSUE TITLE
Clicking on the widget does not open the app

### ISSUE THREAD

**Issue by rimugu** [woheller69/weather#33]
**Describe the bug**
The widgets display the information, but don't open the main app when you tap on them.

**How to Reproduce**
1. Add a widget
2. Tap on the widget (refresh works)
3. Nothing happens

**Expected behavior**
Application opens to see all the information.

**Environment (please complete the following information):**
 - App version:4.4 from f-droid
 - Android version: 10
 - Device: ulefone armor x8

**Comment by woheller69** [comment]
that is intended behaviour. The widget only supports refresh.

**Comment by woheller69** [comment]
will be added in next release
