### ISSUE TITLE
Add Probability of precipitation

### ISSUE THREAD

**Issue by jwsp1** [woheller69/weather#35]
[According to openweathermap](https://openweather.co.uk/blog/post/new-probability-precipitation-openweather-forecasts), Probability of precipitation is distributed by [one-call-api](https://openweathermap.org/api/one-call-api). 
It is available hourly (hourly.pop) and daily (daily.pop). 
Not 100% sure though if it's available in the free version?

(sorry, this is meant to be labeled as "enhancement", not "bug")

**Comment by woheller69** [comment]
Probability of rain is a parameter which will probably not be understood by most users.
I therefore have no plans to add this parameter to keep things simple.

https://www.weather.gov/media/pah/WeatherEducation/pop.pdf

**Comment by kojid0** [comment]
I understand that you are afraid that it will be too complicated for some. Simplicity is important, but I personally find the rain probability a useful piece of information to see if the rain icon really brings rain, or just clouds with a higher probability.
