### ISSUE TITLE
Daily Widget: too large + wrong borders

### ISSUE THREAD

**Issue by kojid0** [woheller69/weather#36]
The Daily Widget is 2 * x (e.g. 2 * 4 in the screenshot) big, but cannot be decreased to 1 * x. Which is odd because the content height would fit in 1 * x.
![Screenshot_20220111-123227](https://user-images.githubusercontent.com/24477557/148936384-30aab8fa-09b6-4be5-ba75-3814d4bec6bc.png)

Also, the distance between Mi-Do and Do-Fr is different than Di-Mi and Fr-Sa. This is more visible when I decrease it to 2x3:
![Screenshot_20220111-124013](https://user-images.githubusercontent.com/24477557/148936393-94018127-8012-447f-ab35-d9d514546c27.png)

**Comment by woheller69** [comment]
I agree. But I do not know how to change this. If someone can provide better layout xmls for the widgets please let me know...

**Comment by woheller69** [comment]
I made some changes. Please try. Just remove .zip

[app-release.apk.zip](https://github.com/woheller69/weather/files/7854438/app-release.apk.zip)

**Comment by kojid0** [comment]
Thank you, going in the right direction.
Two things:
1) Blue Temperature is slightly cut at the bottom. There is plenty of room at the top where the day is.
2) 1x5 widget, as shown in the screenshot, has blanks on the left and right. Strteching the 5-day forecast or making it to a 6-day forecast would be nice.
![Screenshot_20220112-133853](https://user-images.githubusercontent.com/24477557/149142406-9dd13fff-e822-40d4-a6d3-901ea3bf6215.png)

**Comment by woheller69** [comment]
Unfortunately that is very device dependent. On my devices it is not cut off.
Another minor change. I slightly reduced padding at bottom and top.

[app-release.apk.zip](https://github.com/woheller69/weather/files/7854719/app-release.apk.zip)

**Comment by kojid0** [comment]
Looks good now! I'll close this issue :)

**Comment by kojid0** [comment]
BTW one question: do you think you have skills to update the 3x3 widget? Because there's much unused space as well (see screenshot). Additionally, things like the hour stamps for the next-hour-weather-icons are missing as well as minute stamps for the rain-forecast. 
I could create a simple graphical mockup if you want.

![Screenshot_20220112-143456](https://user-images.githubusercontent.com/24477557/149150381-6e270af6-9870-4ca8-9138-468fec7b30d9.png)

**Comment by woheller69** [comment]
I also changed this widget a little. But again this stronly depends on the grid for icons on your screen. On my tablet it looks like your screenshot on my phone there is a lot less space left.
Time stamps would kill the wigdet in my view. On the widget you see how weather will evolve at first glance. For details the app should be opened

**Comment by woheller69** [comment]
I found the bug in the original 5 day widget. I changed it again. Now it should stretch and have equal distances between the columns.
[app-release.apk.zip](https://github.com/woheller69/weather/files/7858257/app-release.apk.zip)

**Comment by kojid0** [comment]
Looks amazing! Have nothing to add :-)

**Comment by kojid0** [comment]
> Time stamps would kill the wigdet in my view. On the widget you see how weather will evolve at first glance.

Created a mockup and shared it in a new issue.
