### ISSUE TITLE
New Type Of Widget

### ISSUE THREAD

**Issue by kojid0** [woheller69/weather#37]
I created a simple mockup with stuff better arranged. 
The current widget has plenty of unused room and some information missing. Also, it was difficult to read at a first glance since time stamps for next-hour-weather-icons were missing.
Feedback welcome and I'm open for discussion.

![grafik](https://user-images.githubusercontent.com/24477557/149239458-d58e5569-3971-46f3-868f-3ba8721e69bb.png)

**Comment by hejops** [comment]
I think it looks great; only thing I would suggest is replacing the precipitation "boxes" with some kind of numerical metric, maybe maximum precipitation in the coming hour (which I assume is the most useful for the average user). Then you could group that precipitation metric with the current temperature and wind speed for a cleaner summary.

The thing I'd most like to see is a chart-type widget with temperature as the bare minimum; this is already implemented in the "Chart" section, so turning that into a widget hopefully shouldn't take too much work. Introducing further customisation options in future would be nice, as I've yet to see an open-source weather widget that matches the capabilities of [Meteogram](https://play.google.com/store/apps/details?id=com.cloud3squared.meteogram) (freemium).

**Comment by peter-czy** [comment]
The suggested widget contains all important information, I like. But isn't UV index number missing?


> The thing I'd most like to see is a chart-type widget with temperature as the bare minimum; this is already implemented in the "Chart" section, so turning that into a widget hopefully shouldn't take too much work. Introducing further customisation options in future would be nice, as I've yet to see an open-source weather widget that matches the capabilities of [Meteogram](https://play.google.com/store/apps/details?id=com.cloud3squared.meteogram) (freemium).

What about making the diagram (inside the app) a widget?

**Comment by woheller69** [comment]
I currently have no plans to add a new widget...

**Comment by kojid0** [comment]
> I currently have no plans to add a new widget...

Sad to hear, but ok. Let's hope somebody else has the knowledge and willpower to do

**Comment by woheller69** [comment]
I will change the day widget as shown below. Weather icons for the upcoming hours will be shown in a clock style.
Wind will be shown with a colored flag for each hour like in the 5 day widget. Also added the min/max temperature for the day.
If someone wants to test: an .apk is also attached. Just remove .zip and install.

![weather_widget_preview](https://user-images.githubusercontent.com/68678880/158076977-1a9ad0ab-90fd-4c03-88cd-ecbd29b59d64.png)
[app-release.apk.zip](https://github.com/woheller69/weather/files/8240510/app-release.apk.zip)

**Comment by kojid0** [comment]
Looks good! Very innovative idea with the clock-style layout.
Bft is missing, is this intentional? What about moving UV indicator (and Bft) next to current temperature? Because the clock-style layout is messy enough... Something like this 
![grafik](https://user-images.githubusercontent.com/24477557/158233099-29f70309-ed69-4b31-bd5f-e6f1366e6409.png)

**Comment by woheller69** [comment]
Bft is removed intentionally. In the widget it is replaced by the colored flag, e.g yellow for >= 5Bft
For more details you can always click on the widget and open the app.
I played around with the UV position and think the current position is the best, but that needs to be tested for a few days.

**Comment by woheller69** [comment]
Coming in V5.2
