### ISSUE TITLE
Not work only error when update weather

### ISSUE THREAD

**Issue by gentr** [woheller69/weather#39]
**Describe the bug**

**How to Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - App version: [e.g. v1.6]
 - Android version: [e.g. 10]
 - Device: [e.g. Google Pixel 4]

![Screenshot_2022-01-22-15-22-37-097_org woheller69 weather](https://user-images.githubusercontent.com/33761976/150642265-8eccaa99-2422-4308-a912-93cd0e2bc9b9.jpg)

**Comment by woheller69** [comment]
which Tirana is this?

**Comment by woheller69** [comment]
do other cities work? Did you enter a valid API key? It can take a while until a key works

**Comment by gentr** [comment]
![Screenshot_2022-01-22-15-35-40-610_org woheller69 weather](https://user-images.githubusercontent.com/33761976/150642877-8f25a090-6548-416e-b36e-5aba36602a78.jpg)

**Comment by gentr** [comment]
Three city and any one not work

**Comment by woheller69** [comment]
then there is probably an issue with your API key from OpenWeatherMap. Is this a new key?

**Comment by gentr** [comment]
Yesterday installed chose city not working, uninstall and reinstalling again, same issue, uninstall and reinstalling again today same issue, I don't know which is the  problem but maybe not the apps not connecting to openweathermap

**Comment by woheller69** [comment]
did you enter your own API key in settings?

**Comment by gentr** [comment]
No, I choice a api from Photon api

**Comment by woheller69** [comment]
Photon API only searches cities. To get weather data you need to register at OpenWeatherMap as described in the app intro and enter it in settings

**Comment by gentr** [comment]
in the old version you entered a public api key and we did not need to open an account in openweathermap, it does not make sense for me to give openweathermap my email to get weather on your apps. I use open weather directly and not need any account or GPS to open. Is your apps and I respect that.

**Comment by woheller69** [comment]
The problem is, there is no public API key. For OneCallAPI OpenWeatherMap only allows 1000 API calls per day. So everyone needs his own key. You can use privacy friendly weather which is "the old version" from which I forked RadarWeather.
They have several public keys and lots of problems with that...
