### ISSUE TITLE
24-hour format not respected in rain radar view

### ISSUE THREAD

**Issue by xandro0777** [woheller69/weather#40]
Despite 24h format enabled, the time is still displayed as am/pm.

**Comment by woheller69** [comment]
I will try with .toLocaleString(navigator.language, { hour12: false })

**Comment by woheller69** [comment]
Please try. Just remove .zip and install.

[app-release.apk.zip](https://github.com/woheller69/weather/files/7963440/app-release.apk.zip)

**Comment by xandro0777** [comment]
Not sure if webview is affected, Chrome needs ```{ hourCycle: 'h23'}``` because of its 24 hours bug where it displays for example 24:15 instead of 0:15. So far it seems to work, hope I remember to look after midnight.

**Comment by woheller69** [comment]
have you seen any problems after midnight?

**Comment by woheller69** [comment]
Will try { hourCycle: 'h23'} instead of { hour12: false }

**Comment by woheller69** [comment]
with hourCycle: 'h23'

please try again and let me know if it works

[app-release.apk.zip](https://github.com/woheller69/weather/files/8004995/app-release.apk.zip)

**Comment by xandro0777** [comment]
Unfortunately doesn't work, between 0-1 hours it displays "FRAME TIME".

**Comment by woheller69** [comment]
maybe webview dependent. Can you try this code:

const event = new Date(Date.UTC(2022, 01, 04, 23, 30, 0));
console.log(event.toLocaleString('en-GB', { hourCycle: 'h23'}));

e.g. paste and run here:
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString
should show : > "05/02/2022, 00:30:00"

**Comment by woheller69** [comment]
For me it works well. I made another change. The rain radar now shows the local time of the watched city.
[app-release.apk.zip](https://github.com/woheller69/weather/files/8008929/app-release.apk.zip)

**Comment by xandro0777** [comment]
> maybe webview dependent. Can you try this code:
> 
> const event = new Date(Date.UTC(2022, 01, 04, 23, 30, 0));
> console.log(event.toLocaleString('en-GB', { hourCycle: 'h23'}));
> 
> e.g. paste and run here:
> https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString
> should show : > "05/02/2022, 00:30:00"

seems to work, I hope the code was really executed by webview and not
by mozilla.org!
