### ISSUE TITLE
Option to not loop rain radar time shift

### ISSUE THREAD

**Issue by xandro0777** [woheller69/weather#41]
Sometimes it is nice to have it loop but often the opposite, so it would be nice to have an option or extra button for that. 

Also, when looping it might be nice to pause for a second or so every time it wraps around.

Finally.. if older data is available from previous invocations it might be nice to extend the view into history.

**Comment by woheller69** [comment]
you can always step through the rainradar manually.
There is already a small break at the end of the loop

**Comment by woheller69** [comment]
Will increase delay at end of loop

**Comment by xandro0777** [comment]
Specifically when manually singlestepping I do not want to wrap over several hours backward. Just want to step as far into the future as it goes.

**Comment by xandro0777** [comment]
Sorry,  didn't manage to test earlier but it has indeed inherited  the 24:35 bug.
