### ISSUE TITLE
Widget not updating regularly

### ISSUE THREAD

**Issue by xandro0777** [woheller69/weather#42]
Hi, I notice that the widget sometimes does not update for very very long time.  Not only is weather data not updated but also it still shows Thursday at Friday noon.

It isn't even updated when I invoke the main app, the app updates its data immediately but the widget is left unchanged.

I typically have it set to update each 1-2 hours and I noticed that if I change this setting it does sometimes update.

This is on Android 11.

**Comment by woheller69** [comment]
The widget updates automatically independent of the main app. Maybe you need to delete the widget and add it again.
The 5-day widget auto updates every 6h, the widget for current weather every 30min.
Some manufacturers have implemented hostile energy management options. see https://dontkillmyapp.com

**Comment by woheller69** [comment]
If you invoke the main app the widget will only update if the city is updated kn the main app.
You can also press the update button on the widget at the upper right

**Comment by xandro0777** [comment]
I think I had the WIFI turned off overnight, so if the app doesn't listen to network available events but updates at fixed times it could fail to update very easily.

The 5 day widget doesn't have any update button?

Also think that the even in the 5 day widget the display of the current day values should be updated if the app reads them for some other reason?

Even if the app doesn't update its weather data it might be a good idea to change the values to reflect the rest of the day - in the evening I don't need to know the temperature that was forecasted for noon that day.

**Comment by woheller69** [comment]
The 5 day widget also updates if the location is updated in the app. The 6h cycle is just additional
