### ISSUE TITLE
pt_BR Translation Proposal

### ISSUE THREAD

**Issue by zehrique** [woheller69/weather#44]
Hi, @woheller69.

I just installed you very good app on my Android smartphone and I liked it very much and would like to know if you are interested in having its strings translated into Brazilian Portuguese (pt_BR).

I would be very happy doing this job for you and sharing the app with the portion of Brazilian people who doesn't speak English.

Please, drop me a line telling me what to do.

Thank you.

**Comment by woheller69** [comment]
sure. Ideal would be a pull request with the strings.xml in the new pt_BR values folder and
also a new directory in fastlane with translation of the descriptions for F-Droid.

**Comment by zehrique** [comment]
OK! I will do it.

**Comment by zehrique** [comment]
Well, I must confess that I'm facing difficulties to make a pull request with my changes.
Could you help me with this issue?
Thank you! :)

**Comment by woheller69** [comment]
fork my latest repo
Add your changes
Commit changes
Push to your fork
open pull request on Github

**Comment by woheller69** [comment]
if you have problems just upload strings.xml and short and long description here

**Comment by zehrique** [comment]
OK!

**Comment by woheller69** [comment]
but it seems you made it

**Comment by woheller69** [comment]
I think if you remove the changelogs and images folder from fastlane I could merge

**Comment by woheller69** [comment]
removed the directories myself.
No more changes required.
Will merge soon.

**Comment by woheller69** [comment]
is this a general Portuguese translation or Brazilian?
For Brazilian the values folder should be
values-pt-rBR instead of values-pt
Of course it would be great if Potuguese people could also live with it.

**Comment by zehrique** [comment]
Well, I translated using Brazilian Portuguese.
You can change the folder name to values-pt-BR if you think it is better.

**Comment by woheller69** [comment]
I will leave it as it is. If some Portuguese complain about strage translations we can split it up later

**Comment by zehrique** [comment]
OK!

**Comment by zehrique** [comment]
Sorry to bother you. Unfortunately I found some typos and strings without translation.

**Comment by woheller69** [comment]
published as V4.9
