### ISSUE TITLE
Edit location name?

### ISSUE THREAD

**Issue by xandro0777** [woheller69/weather#49]
Hi, when adding a location with photon the name/label displayed in the app is sometimes pretty bad and I see no way to change it.

Examples - search "Passo Pordoi", results in French and Italian names displayed. Search for Giumaglio, results in Maggia being displayed.

**Comment by woheller69** [comment]
Where is the problem?
For me Giumaglio works well, see screenshot.
![Screenshot_20220304-195043_RadarWeather](https://user-images.githubusercontent.com/68678880/156824156-991b7e3f-0c51-4682-93d5-a100cfafe04b.jpg)

But I have no influence on the return values from this API.
Sometimes it helps to add the ZIP code.

**Comment by xandro0777** [comment]
The problem comes later on, select  Giumaglio and see what is displayed as label.

The problem is even bigger for Passo Pordoi.

**Comment by woheller69** [comment]
It shows "Maggia" but that is what the API returns as "name" and I have no influence on that.
You can try the API here: https://photon.komoot.io/ and create an issue there if something is wrong 
https://github.com/komoot/photon

**Comment by xandro0777** [comment]
> But I have no influence on the return values from this API.
> Sometimes it helps to add the ZIP code.


I understand that the API may be buggy or simply return strange data
that someone entered into OSM. That will always happen as it does not
seem to be an authoritative database.

At other times the API may return something that is correct but simply
unwieldy as name/label or the user has his own idea what should be
displayed.. for example displaying "Home" instead of some complicated
village name.

So it would be nice if those labels could be edited.

**Comment by woheller69** [comment]
Please try this. (Remove .zip from filename and install)

You can rename the locations with a click in manage locations activity.

[app-release.apk.zip](https://github.com/woheller69/weather/files/8189233/app-release.apk.zip)

**Comment by xandro0777** [comment]
That  works fine.

One unrelated bug, when searching a location by photon screen rotation makes the list of suggestions disappear. This can be annoying - typically there will be a few very similar suggestions and people will be tempted to get more information by rotating the device.

**Comment by woheller69** [comment]
-> V5.1
