### ISSUE TITLE
Blackberry Keyone

### ISSUE THREAD

**Issue by grizzly8u** [woheller69/weather#5]
RadarWeather App won't update forecast. API generated at OpenWeather and entered without issue but no joy on updates of weather. Locations took fine.

**Comment by woheller69** [comment]
Have you removed the "-" which is the placeholder for the API key?

**Comment by grizzly8u** [comment]
Well of course not. Thanks!
--
Sent from my Android phone with GMX Mail. Please excuse my brevity.

woheller69 <notifications@github.com> wrote:

Have you removed the "-" which is the placeholder for the API key?

**Comment by grizzly8u** [comment]
See subsequent reply. "-" was the problem
--
Sent from my Android phone with GMX Mail. Please excuse my brevity.

woheller69 <notifications@github.com> wrote:

Does the app show error messages? Maybe a problem with the key. Witch location did you try?

**Comment by woheller69** [comment]
OK, great. Will make this more clear in next version
