### ISSUE TITLE
Some symbols not displayed

### ISSUE THREAD

**Issue by xandro0777** [woheller69/weather#50]
Hi, on my Android 11 device some symbols are not displayed, seems like the chars are missing in the font?

![photo_2022-03-04_18-56-07](https://user-images.githubusercontent.com/43711649/156816761-34b6e759-8fa4-4b0a-a8f3-fb35e465388b.jpg)

**Comment by woheller69** [comment]
There is nothing missing. Symbols are explained in the legend
