### ISSUE TITLE
Feature: Add pressure forecast in the day and week view

### ISSUE THREAD

**Issue by barefootstache** [woheller69/weather#57]
The pressure feature is already available in the "NOW" panel. It would be nice to have it also available in the hourly forecast in the "DAY" and "WEEK" panels. The reasoning behind the addition, is that people who suffer from joint related pains due to the weather can better plan for the future.

In the case that it might be too bloated, one could add a setting to turn it on and off.

**Comment by woheller69** [comment]
You are lucky, pressure is available in the app database already. So adding it was easy.
Please try. Remove .zip and install the apk.

But for normal use I think it is too much, so I added a switch in preferences.

[app-release_pressure.apk.zip](https://github.com/woheller69/weather/files/8793986/app-release_pressure.apk.zip)

**Comment by barefootstache** [comment]
I followed your steps and for some reason was not able to install the apk. It works fine on the emulator.

Model: King Kong 3, Cubot
Android: 8.1

**Comment by woheller69** [comment]
You have to uninstall first, because it is signed with another key

**Comment by woheller69** [comment]
-> V5.4
