### ISSUE TITLE
Weird characters

### ISSUE THREAD

**Issue by blogdemoi** [woheller69/weather#58]
Hi,
I have weird characters showing (please, see screenshot below).
What can be wrong? I am using a Pixel 4a with the latest GrapheneOS installed.
Thank you.
![Screenshot_20220602-203943_1](https://user-images.githubusercontent.com/83965802/171703807-6e387af9-beb2-430d-b0f2-2f2e7cd40de7.png)

**Comment by woheller69** [comment]
everything is fine, see description below

**Comment by blogdemoi** [comment]
Oh, sorry for this... I am so absent minded. Thank you for this very useful application.
