### ISSUE TITLE
Separate snow indicator

### ISSUE THREAD

**Issue by MisterY** [woheller69/weather#6]
Hi!

Very convenient app with nicely laid-out information on one page.
One request I'd have is to add a separate Snow indicator. OWM provides this information and it could be used to add a separate numeric values, as well as indicate it in the graph.
Thanks!

**Comment by woheller69** [comment]
I thought about that in the past but decided to add rain and snow in order to keep the layout simple. In the end you get wet...
From the weather image above you can always see whether it is rain or snow.
