### ISSUE TITLE
Difference sunset/sunrise with widget

### ISSUE THREAD

**Issue by Spielmops** [woheller69/weather#60]
I am at the polar circle in Norway and I've set the location to "Mo i Rana". The app shows sunset/sunrise with up --:-- and down --:--, which is at this time of the year correct. The widget shows up 02:00 and down 02:00. Both should be the same in the app and within the widget.

Spielmops

**Comment by woheller69** [comment]
Thanks, will be fixed in next release. I obviously forgot to copy that line of code to the widget.
The icons in the widget are all day icons now, right?

**Comment by Spielmops** [comment]
Yes

**Comment by woheller69** [comment]
-> V5.4
