### ISSUE TITLE
Location name switching to coordinates

### ISSUE THREAD

**Issue by oliver-cfc** [woheller69/weather#61]
**Describe the bug**
After adding a location using photon, the name changes to the coordinates after the first automatic refresh (I think that's the trigger)

**How to Reproduce**
1. Add a new location
2. See your location name in the app and widget
3. After a while (I assume this is the refresh) the name switches to the coordinates

**Expected behavior**
Always use name for location

**Screenshots**
See four screenshots
1) What I want to see
2) Working in app
3) Working in widget
4) Switched to coordinates in 'locations.'  This cascades down to the app and the widget.

Apologies if github is not resizing these images and they can still be seen from the moon.

![01_location_with_name](https://user-images.githubusercontent.com/1508844/175776265-8c42ad0e-47fa-4b7e-aeaa-eac4ae5a9e1b.png)
![02_app_with_name](https://user-images.githubusercontent.com/1508844/175776308-d8e0704f-a67b-4cd0-8539-abbca99bc83b.png)
![03_widget_with_name](https://user-images.githubusercontent.com/1508844/175776330-cd79331a-23d0-4c18-81c0-560b1b1eb91d.png)
![04_location_changed_to_coordinates](https://user-images.githubusercontent.com/1508844/175776355-37fe9a44-f72c-4d11-9e09-4f75c14bf587.png)

**Environment (please complete the following information):**
 - App version: 5.3 (this is the first version I've tried, don't know if it exists in previous)
 - Android version: 11
 - Device: LG K51

**Comment by woheller69** [comment]
That is inteded behaviour. The first TAB is always used for GPS if activated.
Just add your location in another position

**Comment by oliver-cfc** [comment]
Thanks for clarifying. Makes sense to me now.
