### ISSUE TITLE
API Key does not work - please try APK from here

### ISSUE THREAD

**Issue by Ilav1** [woheller69/weather#62]
**Describe the bug**
I created an OWM account over (link in the app). 
24h later the Key is still not working with the app. OWM support said, that the key is activated and can be used. So there has to be a problem with the app. I got the same problem in other weather apps too.  So maybe there is something chanced by OWM? 

**How to Reproduce**
1. Settings --> API Key --> OK
2. Left side menu --> Add an location
3. Left side menu --> weather
4. Error --> can't get the data. Try again later. 

**Environment (please complete the following information):**
 - App version: 5.5
 - Android version: 10
 - Device: Huawei P Smart 2019

**Comment by woheller69** [comment]
Yes, they said they would deactivate OneCallAPI with 1000 free calls for new accounts. Obviously that happened now.
You can subscribe to the new OneCallAPI 3.0 which is free up to 1000 calls per day and charged above that limit. 
I will need to change my app to support that. 
I will try to make test version next week. Unfortunately I cannot test myself. My old account will continue to work with the old OneCallAPI and I do not want to change my subscription.

**Comment by Ilav1** [comment]
In my account there is the free plan of the "professional collections" activated. There are 60  calls per minute free. This is the problem?

I can test the new app version(s) if you want. Just let me know :)

**Comment by woheller69** [comment]
You will need a subscription for OneCallAPI 3.0.
If you set the limit to 1000 calls per day it should be free.
But they also changed the URL for it, so I need to change the app.

**Comment by woheller69** [comment]
You can test with a webbrowser.
Insert latitude, longitude, and API key. (Without brackets)

https://api.openweathermap.org/data/3.0/onecall?lat={lat}&lon={lon}&appid={API-Key}

The app at the moment uses .../2.5/...

**Comment by Ilav1** [comment]
> You can test with a webbrowser. Insert latitude, longitude, and API key. (Without brackets)
> 
> [https://api.openweathermap.org/data/3.0/onecall?lat={lat}&lon={lon}&appid={API-Key}](https://api.openweathermap.org/data/3.0/onecall?lat=%7Blat%7D&lon=%7Blon%7D&appid=%7BAPI-Key%7D)
> 
> The app at the moment uses .../2.5/...

When I insert my key and long lat it's not working.

The OWM support gave me this link to show me that the key is working:

https://api.openweathermap.org/data/2.5/weather?q=London&units=metric&appid={API-Key}

This link is working fine but it's different from yours... It's .../2.5/... not... /3.0/... And doesn't use long/lat

The link above (OWM Support) with... /3.0/... ends in an internal error.

**Comment by woheller69** [comment]
It should end with

    {"cod":401, "message": "Invalid API key. Please see 
    http://openweathermap.org/faq#error401 for more info."}

if you do not have the subscription for OneCallAPI 3.0

The other link with 2.5/weather is not sufficient for my app.
That is an old API which has less information and has been replaced in my app a few years ago - when they promoted their new OneCallAPI. Now they switched it off for new users and replaced it with OneCallAPI 3.0.
No idea why. If you set your limit to 1000 it is as free as it was before with OneCallAPI 1.0 ...

**Comment by Ilav1** [comment]
This is the message when I'm using your link with my data.

There is no option to subscribe to the "One Call by Call" plan (One Call API 3.0) for free. I still have to enter billing informations in my account. I will contact the OWM support in order to get further information.

**Comment by woheller69** [comment]
As far as I understand you have to enter billing information but you will not be charged as long as you stay below 1000 calls per day

**Comment by Ilav1** [comment]
The support told me the same.

Is it possible to use the other OWM subscription option when it is changed in the app?

I don't want to spread my data specially when they will not be used.

I don't know why they changed it because you can limit the calls to 1000 per day and this is for free.
So why I can't subscribe without billing information as long as the calls are limited under 1000?
Maybe it's a capitalism thing. :/

**Comment by woheller69** [comment]
The app will need OneCallAPI 3.0
The other API does not provide all the information.

Yeah, probably this is a capitalism thing. Maybe they want to go public and need subscribers for their paid subscriptions. Even if you stay below the limit...

**Comment by woheller69** [comment]
Please try this version if you have a free subscription + OneCallAPI 3.0 subscription with a limit of 1000 calls / day
Remove .zip and install.
In settings enter API key and check the box at OneCallAPI 3.0.

[app-release_OneCall3.apk.zip](https://github.com/woheller69/weather/files/9382752/app-release_OneCall3.apk.zip)

**Comment by Ilav1** [comment]
I tried the app with the free subscription and set the limit to 1000 calls/day but still have no billing details (just credit cards accepted).

With this combination its not working still with and without checked box (One Call API 3.0).

It would be fine to get access to the data without filling the billing details. Otherwise every new user of the app has to spread there billing details to OWM. I thing it's a reason not to use apps like yours.

**Comment by Ilav1** [comment]
I tried the app with the free subscription and set the limit to 1000 calls/day but still have no billing details (just credit cards accepted).

With this combination its not working still with and without checked box (One Call API 3.0).

It would be fine to get access to the data without filling the billing details. Otherwise every new user of the app has to spread there billing details to OWM. I thing it's a reason not to use apps like yours.

**Comment by Ilav1** [comment]
I tried the app with the free subscription and set the limit to 1000 calls/day but still have no billing details (just credit cards accepted).

With this combination its not working still with and without checked box (One Call API 3.0).

It would be fine to get access to the data without filling the billing details. Otherwise every new user of the app has to spread there billing details to OWM. I thing it's a reason not to use apps like yours.

**Comment by woheller69** [comment]
With free subscription only it cannot work...

You should be able to use Forecastie which does not use OneCallAPI

**Comment by woheller69** [comment]
is requesting billing information for the 1000 free calls is against GDPR data minimization principle?

**Comment by Ilav1** [comment]
> is requesting billing information for the 1000 free calls is against GDPR data minimization principle?

Maybe but I dont know the details about the GDPR / DSGVO.

In my opinion it makes no sense to enter the billing data as long as the limit is set to 1000 calls/day.
By default the limit is set to 2000 calls/day, so you have to pay, but below 1000 you don't have to.

**Comment by oliver-cfc** [comment]
I'm using the 3.0 apk and the API calls are working as expected with my new 3.0 subscription. However, on the "clock face" widget I dont see the icons around the outside that show sun/rain etc. Is this related to the out-of-schedule apk?
![Screenshot_20220820-125101](https://user-images.githubusercontent.com/1508844/185757987-403ae3d9-787f-4af8-a0ec-f8e69d2ef556.png)

**Comment by woheller69** [comment]
Is 2days / 1h + 5days / 3h activated in settings?
Do you have hourly forcasts in the app?

**Comment by oliver-cfc** [comment]
> Is 2days / 1h + 5days / 3h activated in settings? Do you have hourly forcasts in the app?

Gahh... no, I had the 5 day / 3 hour setting enabled. All is good now, thanks.  
The 3.0 apk is working great for me.

**Comment by woheller69** [comment]
Can you please also test this version?
Does it show one more day in week forecasts (OneCallAPI 3.0 should have one day more).
Please add a screenshot with the week forecast and chart.

[app-release_OneCall3_V2.apk.zip](https://github.com/woheller69/weather/files/9388492/app-release_OneCall3_V2.apk.zip)

**Comment by fairking** [comment]
![Screenshot_20220821-123254](https://user-images.githubusercontent.com/13495631/185788937-f73e6613-9e35-4794-a152-2dbc449defe0.png)

**Comment by fairking** [comment]
![Screenshot_20220821-124024](https://user-images.githubusercontent.com/13495631/185789204-6ae6c601-5cd4-4612-86f0-4dd6d38b1ed5.png)

**Comment by oliver-cfc** [comment]
> Can you please also test this version? Does it show one more day in week forecasts (OneCallAPI 3.0 should have one day more). Please add a screenshot with the week forecast and chart.
> 
> Remove .zip and install [app-release_OneCall3_V2.apk.zip](https://github.com/woheller69/weather/files/9388492/app-release_OneCall3_V2.apk.zip)

Don't know if I'm looking in the right place but the first test apk showed 8 days for the 'week' and 'chart' cards (Sunday through Sunday.) I have a couple of screenshots but won't post unless requested because you can see them from the moon.
Can't say I noticed what it was on the old 2.5 API.    

Here's a screenshot after upgrading to the second APK which still shows 8 days for both.
![Screenshot_20220821-064900](https://user-images.githubusercontent.com/1508844/185800117-2ea59f51-0536-4c24-a631-f74d31576a3f.png)

**Comment by woheller69** [comment]
did you activate the checkbox for API 3.0 in settings?

**Comment by woheller69** [comment]
you do not need OneCallAPI 3.0 if you have an old account (prior to Aug 15, 2022 (?)). Then the old OneCallAPI will continue to work

**Comment by oliver-cfc** [comment]
> did you activate the checkbox for API 3.0 in settings?

Yep. 3.0 is definitely checked.  If I uncheck it I get an error when trying to update.
I had an old API that I generated years ago and it was working as expected. Then on Saturday I decided to update my email on OWM away from a gmail one. While there I generated a new key so I could give it a name, deleted the old key, updated things in radarweather and thats when the app broke.  I came to github and found this bug report.

**Comment by woheller69** [comment]
ok. According to their specs OneCall 1.0 should give 7 days forecast, 3.0 should give 8 days. Maybe that is not true. The code is dynamic now...

**Comment by oliver-cfc** [comment]
> ok. According to their specs OneCall 1.0 should give 7 days forecast, 3.0 should give 8 days. Maybe that is not true. The code is dynamic now...

Well... I am getting 8 days (sun --> sun inclusive) and I got that with both 3.0 APKs.  I just dont remember what it was on the old API.

**Comment by woheller69** [comment]
it is the same

**Comment by woheller69** [comment]
Fix is published

**Comment by woheller69** [comment]
In case of problems with OpenWeatherMap API keys, try my omWeather https://github.com/woheller69/omweather based on open-meteo.com (open source, no key required)
