### ISSUE TITLE
Widget issues (GPS location and Black Mode)

### ISSUE THREAD

**Issue by fliegentoeter** [woheller69/weather#64]
Hi,

I found three issues with the widget that bother me:
- I switched on GPS-Location and the widget displays degrees and not the nearest city or just "current location"
- Android 10+ Dark Mode is not black. Is there a way for a proper black mode for oled-screens? Looks kind of "cheap" on a black wallpaper. I would prefer a black background and no grey boxes around temperatue and so on
- My Update Intervall is set to 2 hours but the app/or the widget seems to update my location way more frequent than 2 hours. (Turned off Location Permission for all other apps and noticed the icon frequently.)
Here a Screenshot how it looks like on GrapheneOS: 
![Screenshot_20220907-144135](https://user-images.githubusercontent.com/8972985/188882763-001376ca-af75-4c04-bcb6-688c89ce16c0.png)

**Comment by woheller69** [comment]
The widget updates every 30min. If GPS is enabled it will listen to position updates (Update min interval 10 min,  with min position change of 5km) and may update more frequently if needed).
In the first Tab and in the widget the coordinates are shown in this case.

It is dark mode, not black mode...

**Comment by fliegentoeter** [comment]
Can't I change this to the automatic update behavior which is set in the app? Seems like a waste of battery life to me that way.

Can i disable the coordinates? Even if i change the name of the location to "current location" in the app, after the next update the widget and the app show these coordinates again. (I do not understand who would find these coordinates more useful than the next big city or just "current location".)

I know, but it looks out of place on modern oled-screens :)

**Comment by woheller69** [comment]
If you use the widget the 30min interval is set. But as long as the screen is off Android usually waits until the screen is switched on before it updates. So the battery is not affected a lot.

Coordinates cannot be disabled at the moment.

**Comment by fliegentoeter** [comment]
That's goot to know, thanks.

I would like it a lot if the widget had some basic settings to at least turn on/off different indicators and color options to integrate it better in different phones. But I do not have any coding skills so I can't help with that.
Anyways, nice app and keep up the good work!
