### ISSUE TITLE
Your device is not connected to the internet error

### ISSUE THREAD

**Issue by mr-ransel** [woheller69/weather#65]
**Describe the bug**
After setting up the app, getting an API key and subscribing to the OneCall API 3.0 with a 1000 call limit and checking it in the app, I only get a "Your device is not connected to the internet" toast error repeatedly. 

Yet my internet works perfectly fine, on both mobile and WiFi data. 

**How to Reproduce**
1. Set up the app and API key, and OneCall checkbox
2. Click refresh

**Expected behavior**
To get the weather data we all so desperately crave. 

**Screenshots**
N/A

**Environment (please complete the following information):**
 - App version: 5.6
 - Android version: Calyx OS, final version
 - Device: Pixel 2

**Comment by woheller69** [comment]
This toast is only shown if api.openweathermap.org cannot be reached.
So either your device is offline or openweathermap does not respond.
Do you still have the problem?

If yes please try these 2 versions (uninstall old version. Remove .zip and install)

[Test1.apk.zip](https://github.com/woheller69/weather/files/9797201/Test1.apk.zip)

[Test2.apk.zip](https://github.com/woheller69/weather/files/9797198/Test2.apk.zip)

Does one of these versions work?

**Comment by woheller69** [comment]
or maybe an issue with a firewall? I am using isReachable()
https://developer.android.com/reference/java/net/InetAddress#isReachable(int)

**Comment by woheller69** [comment]
Have you tried it?

**Comment by mr-ransel** [comment]
Not yet, sorry. I'll give it a try today when I have a minute.

Oct 18, 2022 9:58:15 PM woheller69 ***@***.***>:
