### ISSUE TITLE
Error while updating Forecast, please try again!

### ISSUE THREAD

**Issue by adrian5** [woheller69/weather#66]
Similar to #39 and #62.

A call to `https://api.openweathermap.org/data/2.5/weather?…` works. I don't want to subscribe to the OneCall API, and the feature is unchecked in the settings.

**Comment by woheller69** [comment]
It cannot work without OneCallAPI 3.0 subscription.

You either have a key created prior to ~ Aug 15, 2022 or you need that subscription. 

Some apps have created tons of accounts and added the keys to their code...

https://github.com/SecUSo/privacy-friendly-weather/blob/master/keys.properties

**Comment by adrian5** [comment]
I see, that's unfortunate.

**Comment by keatonhj** [comment]
I'm getting this error and I have already subbed to ghr premium api

**Comment by woheller69** [comment]
see #62 and try links from there in webbrowser with your key

**Comment by woheller69** [comment]
If you have a new key and subscription you need to check this option

![image7](https://user-images.githubusercontent.com/68678880/215355771-96bd8e1e-906c-4f9f-b17c-8d250b20b4f7.png)

**Comment by keatonhj** [comment]
I reinstalled the app (which used to have another key that I just changed in to settings).

This clean install fixed it. Works now.

30 Jan 2023 8:10:11 am woheller69 ***@***.***>:

**Comment by woheller69** [comment]
In case of problems with OpenWeatherMap API keys, try my omWeather https://github.com/woheller69/omweather based on open-meteo.com (open source, no key required)
