### ISSUE TITLE
Feature request: Yesterday weather 

### ISSUE THREAD

**Issue by MartinN3** [woheller69/weather#67]
Hello, 

I really like detailed weather by hour and I would like to see yesterday's weather in app for comparison. Am I being weird here?

Thanks

**Comment by woheller69** [comment]
Yesterday's weather is not available in the API and why do you care about that?

**Comment by MartinN3** [comment]
Ye i tought API might not provide that.

Im riding motorbike and with morning temps vs afternoon temps + rain etc. i can kinda compare what was i wearing yersterday if it was enough or too much.

Thanks anyway for answer and great apps!.
