### ISSUE TITLE
Ayuda 

### ISSUE THREAD

**Issue by Yunier86** [woheller69/weather#68]
Hello previously use the apk without problems now I reinstall it I put my open Weather key but the apk does not work does not find my location and constantly puts me error when updating or that I do not have an Internet connection, please help. **Describe the bug**

**How to Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - App version: [e.g. v1.6]
 - Android version: [e.g. 10]
 - Device: [e.g. Google Pixel 4]

**Comment by Yunier86** [comment]
![Screenshot_20230101-181601](https://user-images.githubusercontent.com/121773584/210187222-4521f7e6-3150-4dfe-90cb-24ba962de976.jpg)

**Comment by woheller69** [comment]
Then there is a problem with you key. Do you have a new key (after mid July 2022)? 
For old key do not check the  OneCallAPI 3.0 option

**Comment by woheller69** [comment]
does that work with your key?

https://api.openweathermap.org/data/2.5/onecall?lat=48.9&lon=13.76&appid=yourkey

**Comment by Yunier86** [comment]
Here's what it puts on me:

{"cod":401, "message": "Clave de API no válida. Consulte https://openweathermap.org/faq#error401 para obtener más información".}

**Comment by woheller69** [comment]
Your key is not valid...
See #62

**Comment by Yunier86** [comment]
Well I solved the problem, I found my first API key when I used the apk for the first time and with this one if it worked for me. Previously the apk gave me the name of the place of my location, now I see that instead it puts the coordinate data of the location, is it normal that it is so?

**Comment by woheller69** [comment]
If the position is determined via GPS you get the coordinates

**Comment by Yunier86** [comment]
> Re: [woheller69/weather] Ayuda  (Issue #68) – If the position is determined 
> via GPS you get the coordinates

Ok 👌

**Comment by Yunier86** [comment]
This weather provider using the apk gives me rain ☔ several times a day 
every day, however it is not so much sun ☀ and heat

**Comment by woheller69** [comment]
In case of problems with OpenWeatherMap API keys, try my omWeather https://github.com/woheller69/omweather based on open-meteo.com (open source, no key required)
