### ISSUE TITLE
Norwegian Meteorological Institute source

### ISSUE THREAD

**Issue by baermathias** [woheller69/weather#69]
What about using data from the Norwegian Meteorological Institute? Their data is open (https://www.met.no/en/free-meteorological-data) and seems to support the whole world. GNOME and KDE Weather both use it as their provider of weather data. Also the project GeometricWeather might use it in future.

**Comment by woheller69** [comment]
my plan is to offer open-meteo at some point in the future.
They will hopefully provide a similar API.

https://github.com/open-meteo/open-meteo/issues/116

**Comment by woheller69** [comment]
Here is my new app using open-meteo

https://github.com/woheller69/omweather

**Comment by baermathias** [comment]
Thank you for your effort! Will you maintain both apps in future? I have installed the new one and uninstalled this one.

**Comment by woheller69** [comment]
will maintain both
