### ISSUE TITLE
Cannot add any city

### ISSUE THREAD

**Issue by AlterDepp** [woheller69/weather#7]
If l try to add a city by typing a name and selecting an item from the dropdown, the location is shown correct on the map, but when I press 'add', the app prints 'no location found'
I tried several cities including Munich and London.

**Comment by woheller69** [comment]
I do not have that problem on any of my devices. Just tried Munich and London. I only get this error if I edit the line when the city is shown on the map and then press add.

**Comment by AlterDepp** [comment]
Still exists on version 1.6

**Comment by woheller69** [comment]
Which Android version / device do you have? Does version v1.1 work?  That was before migration to AndroidX libraries.

**Comment by woheller69** [comment]
Have you uninstalled the app before updating? Did you try the original app Privacy Friendly Weather? Does adding cities work there?

**Comment by AlterDepp** [comment]
I am using android version 10 on a sony xperia xz2c (H8324).
On F-droid I can only find versions 1.4/1.5/1.6
Tried to uninstall and reinstall: no success
Tried Privacy friendly weather: also can’t add locations

**Comment by woheller69** [comment]
I sent you an email with a test build. Please let me know if that helps.

**Comment by woheller69** [comment]
Fixed in V1.7
