### ISSUE TITLE
Apk Release

### ISSUE THREAD

**Issue by meichthys** [woheller69/weather#72]
Would it be possible to release the apk here on Github so we could install without having to use fdroid?

**Comment by woheller69** [comment]
You can directly download the apk from F-Droid if you do not want to use the F-Droid app.
Will not publish apks here

**Comment by woheller69** [comment]
they also support reproducible builds if desired by the author. Then they build it, verify it but use the apk signed by the author

**Comment by woheller69** [comment]
as I do not publish apks I do not need reproducible build...

But it seems you can use Obtainium to update apps from F-Droid

**Comment by woheller69** [comment]
Btw, my new omWeather app has better data in my view and the data provider is also open source
