### ISSUE TITLE
Icon view

### ISSUE THREAD

**Issue by MoonDragon-MD** [woheller69/weather#73]
Hi, I wanted to know if you can fix the rain icons, I only see squares:
![Screenshot_20230510-iconProblem](https://github.com/woheller69/weather/assets/42640027/d4001caa-b910-48f5-9af0-3392ce286106)

Also, I would like to know if it is possible to use external icons for various weather conditions (sunny, rainy, cloudy, etc.), for example, the ones from chronus (com.dvtonder.chronus.miui) are also read by other weather widgets (CyanogenMod, LineageOS, AICP, etc.).

 - App version: 5.9 build 59 (f-droid)
 - Android version: 7.1.2
 - Device: Redmi 4X

Otherwise, everything is fine, and compared to other similar ones, the rainfall radar looks good, great!!!

**Comment by woheller69** [comment]
The squares are correct. See legend.
Other external icons cannot be used

**Comment by MoonDragon-MD** [comment]
> The squares are correct. See legend. Other external icons cannot be used

Thank you for responding,

I can't figure out where to find the legend...

**Comment by woheller69** [comment]
mm/h line on your screenshot...

**Comment by MoonDragon-MD** [comment]
But is it possible to use another type of icon? I have seen for example on a similar fork use a raindrop

**Comment by woheller69** [comment]
Do you mean Privacy Friendly Weather? These drops do have a lot of other problems.

My focus has shifted to my new omWeather app. It unfortunately does not have the 60min forecast, but weather data are much better in my view...

**Comment by MoonDragon-MD** [comment]
> Do you mean Privacy Friendly Weather? These drops do have a lot of other problems.
> 
> My focus has shifted to my new omWeather app. It unfortunately does not have the 60min forecast, but weather data are much better in my view...

I just looked at your new omWeather app, it looks interesting that you can use the API without registration.

Thank you and I wish you good work
