### ISSUE TITLE
Unicode character compatibility issue

### ISSUE THREAD

**Issue by ondern** [woheller69/weather#77]
**Describe the bug**

I am from Turkey. My phone language and everthing set to Turkish.

Some of informations does not seem on user interface and it is broken. Attached SS.

![Screenshot_20230527-142310](https://github.com/woheller69/weather/assets/109258788/282b3314-36b0-4d6e-b99d-5a9b1c085f88)

**Environment (please complete the following information):**
 - App version: [e.g. v1.6] v6.0
 - Android version: [e.g. 10] 13
 - Device: [e.g. Google Pixel 4] Mi9T

**Comment by woheller69** [comment]
All correct
