### ISSUE TITLE
Strange layout on tablets 

### ISSUE THREAD

**Issue by gpopesc** [woheller69/weather#79]
**Describe the bug**
See screen capture 

**How to Reproduce**
See screen capture 
**Expected behavior**
The internal tiles should be vertical align, with vertical scroll
The tiles should be entire screen wide.

**Screenshots**
![Screenshot_20230530_122832_org woheller69 weather](https://github.com/woheller69/weather/assets/11590919/a77f66ac-bbf3-4099-b32b-b10e720261ff)

**Environment (please complete the following information):**
 - App version: 6.0
 - Android version: 10
 - Device: Huawei mate pad 10

**Comment by woheller69** [comment]
For tablets the app uses a grid layout. That is correct
