### ISSUE TITLE
pull weather by openweathermap station id

### ISSUE THREAD

**Issue by yknip0** [woheller69/weather#8]
My weather station pushes to OWM. I would like to see that weather in this app. The closest OWM 'city' is 1000 feet lower and 10miles away my station, with much different weather. An option to enter my station id along with my api key would be nice!

**Comment by woheller69** [comment]
This app uses One Call API which only works with latitude/longitude in requests.
The only thing I might add in future is an option to add own cities based on lat/lon to the internal city list or to select a location from a map.

**Comment by woheller69** [comment]
Maybe you want to try this feature which will come in V1.8.
In manage locations there is a button at the bottom left which allows to edit the city list. There you can select any city you do not need and change the data for your city name, latitude, etc.
Afterwards you can add the city via the normal dialog. Afterwards you should at least get weather data influenced by your own weather station.

**Comment by woheller69** [comment]
Editor available now

**Comment by yknip0** [comment]
I will try this as soon as v1. 8 is available on f-droid. Thank you! 

On March 4, 2021 11:42:55 PM MST, woheller69 <notifications@github.com> wrote:
>Editor available now
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/woheller69/weather/issues/8#issuecomment-791195370
-- 
Sent with K-9

**Comment by woheller69** [comment]
It is on F-Droid already. Let me know if it helps

**Comment by yknip0** [comment]
My updated repositories show v1.17.2 from 12/17/20 (installed). 
-- 
Sent with K-9

**Comment by yknip0** [comment]
Oops, my bad, updating now
-- 
Sent with K-9

**Comment by yknip0** [comment]
I can't get the Form to work for me. Questions:
1. What is "Search location"?
2. Is "Name" constrained, or just any string?
3. The "ID" field does not permit entry. I assume this is for owm weather station ID. What am I doing wrong?

Here's what I entered:
Search location: (left blank) 
Name: Pinos Altos
Latitude: 32.88
Longitude: -108.22
Country code: US
ID: (inaccessible)

When I clicked the Modify button, I saw a one second popup error message "No location found that matches..." 
-- 
Sent with K-9

**Comment by woheller69** [comment]
just search any location you do not need. Then change data and click modify. You cannot add new locations, just change any of the existing

**Comment by yknip0** [comment]
OK, got it. Modified an unused, existing owm city, then added the modified city. So far so good. Appears to be displaying my weather station data! 

Good job, thank you!

Any chance of a simple widget showing, say, current weather icon+temp? 

On March 6, 2021 8:51:52 AM MST, woheller69 <notifications@github.com> wrote:
>just search any location you do not need. Then change data and click modify. You cannot add new locations, just change any of the existing
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/woheller69/weather/issues/8#issuecomment-791975872
-- 
Sent with K-9

**Comment by woheller69** [comment]
maybe in future. I removed all that stuff from the original app because it did not work.

**Comment by woheller69** [comment]
Next release will have a widget

<img src="https://raw.githubusercontent.com/woheller69/weather/main/app/src/main/res/drawable-nodpi/weather_widget_preview.png">

**Comment by yknip0** [comment]
Terrific, thanks for the good work! 
-- 
Sent with K-9
