### ISSUE TITLE
Rain Radar disappears after device rotation

### ISSUE THREAD

**Issue by littlecd** [woheller69/weather#81]
**Describe the bug**
Rain Radar disappears after device rotation

**How to Reproduce**
1. Go to Rain Radar
2. Rotate

**Expected behavior**
Weather map persists there.

**Screenshots**
Before rotation
<img width="315" alt="Screen Shot 2023-09-10 at 8 19 31 PM" src="https://github.com/woheller69/weather/assets/144590216/2fc66a31-19d0-47b7-a231-f78df841796c">

After rotation

<img width="624" alt="Screen Shot 2023-09-10 at 8 19 39 PM" src="https://github.com/woheller69/weather/assets/144590216/5d4c50a2-287a-470e-b917-a40240113245">

**Comment by woheller69** [comment]
Simply click to open again
