### ISSUE TITLE
City's location gets lost after rotation

### ISSUE THREAD

**Issue by littlecd** [woheller69/weather#82]
**Describe the bug**
City's location in the map is lost after rotating device

**How to Reproduce**
1. Go to Manage Locations
2. Click on Add
3. Input a city name
4. Rotate

**Expected behavior**
City's location persists in the map

**Screenshots**
Before rotation

![bug3-before](https://github.com/woheller69/weather/assets/144590216/c29689fe-c6db-4557-9fc0-ab926b009c78)

After rotation
![bug3-after](https://github.com/woheller69/weather/assets/144590216/4884e629-71c1-4d1c-b78f-c2c86780b62c)

**Comment by woheller69** [comment]
Don't rotate while adding a city
