### ISSUE TITLE
Crash when obtaining location 

### ISSUE THREAD

**Issue by christf** [woheller69/weather#83]
**Describe the bug**
When obtaining the location with GPS, the app crashes reproducibly

**How to Reproduce**
1. Go to top right, select gps location 
2. Watch the app crash 

**Environment (please complete the following information):**
 - App version: 6.0
 - Android version: 10
 - Device: shift phone 6mq

**Comment by woheller69** [comment]
update to V6.2

**Comment by christf** [comment]
Thank you, the problem is gone with 6.2.
