### ISSUE TITLE
Feature request: Feels like temperature

### ISSUE THREAD

**Issue by odysss** [woheller69/weather#85]
Is it possible to add the "Feels Like" temperature to the app? Today is only shows the current temperature which might not be the actual temperature you'll feel. From my quick googling it seems this data is already available:

https://openweathermap.org/api/one-call-api

`                

{
  "lat": 33.44,
  "lon": -94.04,
  "timezone": "America/Chicago",
  "timezone_offset": -21600,
  "current": {
    "dt": 1618317040,
    "sunrise": 1618282134,
    "sunset": 1618333901,
    "temp": 284.07,
    "**feels_like**": 282.84,
    "pressure": 1019,
    "humidity": 62,
    ...
  `

**Comment by woheller69** [comment]
I will not add it to RadarWeather. But it is available in my omWeather. 
There you can set a switch to show feels like values instead of normal temperatures

**Comment by Theluga** [comment]
Yes, I would like to have a feels like but not replacing the temperature. Just another line under temperature with the feels like. 
I believe that more information is better than less.

If you could add just a new line with this information would be great. If not, it's alright. 

Thank you for this app. Is the most accurate I have. (the omWeather is unfortunately not accurate in my location)
