### ISSUE TITLE
Feature request: one icon widget

### ISSUE THREAD

**Issue by Miodragz** [woheller69/weather#86]
Greetings, this one should be very easy to implement. Like almost all other weather applications it would be great to have single icon widget which would display weather icon (sun/cloud/rain/snow etc.) and current temperature.

Also it would be great to have clock widget with weather. Very convenient layout would be to have 3 segments, where 1st would be weather icon (cloud/sun/rain etc.) and current temperature below it, than on 2nd segment - clock with date below, and 3rd with next upcoming condition - weather icon and below day / time of prediction.

Here I crafted an example:
![layout example](https://github.com/woheller69/weather/assets/2876961/f1b70452-acb1-4f91-90ad-8a600c6fd141)

Weather pictures used in the example ware downloaded from [https://www.flaticon.com/packs/weather-161](https://www.flaticon.com/packs/weather-161) and are made by user iconixar.

Thanks.

**Comment by woheller69** [comment]
you can try this.
![weather_digital_clock_widget_preview](https://github.com/woheller69/weather/assets/68678880/e68ff2a3-8455-44ce-a23d-a0d70066d8f2)

Uninstall
Remove .zip and install

[app-release.apk.zip](https://github.com/woheller69/weather/files/13515882/app-release.apk.zip)

**Comment by woheller69** [comment]
[app-release.apk.zip](https://github.com/woheller69/weather/files/13515919/app-release.apk.zip)

**Comment by woheller69** [comment]
with date:
![weather_digital_clock_widget_preview](https://github.com/woheller69/weather/assets/68678880/d76c85ad-616f-47b6-bb65-f24c8b575061)
[app-release.apk.zip](https://github.com/woheller69/weather/files/13521803/app-release.apk.zip)

**Comment by Miodragz** [comment]
This is very nice base for further development of UI, but as is, it is already very useful. Further development can be adding zoom capability, ability to make specific icon order, skins, and upcoming alarming next condition is also very useful info to be available.

I will leave this one open in case I think of something else for next interesting upgrade.

Thanks.

**Comment by Miodragz** [comment]
After few weeks of usage, I came to report my observations.

1. UV section has no purpose (at least where I live, it is always present, so that section does not shows any new info)
2. Date representation can be more useful. Display of current year maybe is useful to time traveling old generation terminator... Instead it would be by far more useful to have name of a day. For example an much more useful format would be: "Friday, Jan 12"
3. Instead of UV, AIR pollution information would be of much greater value. Websites such as "https://www.iqair.com/world-air-quality" offer free API tier for members.

There are some more ideas, but for now these should be priority.

Regards, Miodrag.

**Comment by ildar** [comment]
I can't find this "big clock" widget in the latest release. Am I overlooking?
2nd, is it possible to have the transparent background?

**Comment by woheller69** [comment]
there are 3 widgets available as shown here https://github.com/woheller69/weather
and no, transparent background may cause problems depenfing on background color

**Comment by ildar** [comment]
regarding the transparent background there are a couple of ways to cease
problems:
1. change the labels' colors
2. outline the labels with black
3. elegant and difficult way: put a black rectangle to the back with
transparency ~70-80%

I experimented with MinCal, trying different params.
https://f-droid.org/en/packages/cat.mvmike.minimalcalendarwidget/

**Comment by woheller69** [comment]
simpler way: outline whole widget with a semi-transparent background
