### ISSUE TITLE
error while updating forecast, please try again

### ISSUE THREAD

**Issue by Ssyleric** [woheller69/weather#87]
**Describe the bug**
Since the end of November, I think, nothing works just this error appeared.

**How to Reproduce**
1. Go to menu
2. Click on Weather
3. See error "error while updating forecast, please try again"

**Expected behavior**
The updating of the location

**Screenshots**
![Screenshot_20240126_162811_RadarWeather](https://github.com/woheller69/weather/assets/47066760/e7860f55-a8bf-4336-a442-69e93621368b)

**Environment (please complete the following information):**
 - App version: [v6.3]
 - Android version: [14]
 - Device: [Samsung galaxy Zflip5]

**Comment by woheller69** [comment]
Then your internet connection is not working or OpenWeatherMap is down or there is an issue with your API key

**Comment by Ssyleric** [comment]
I'm on my phone, and everything is connected.
I connect to my OpenWeatherMap account add a new api key.

**Comment by woheller69** [comment]
see #39 #62 #66

**Comment by woheller69** [comment]
new keys do not work, only if you subscribe to onecallapi and give them your credit card.

Try omWeather instead

**Comment by marcofeltmann** [comment]
I stumbled upon this as well. Although I subscribed that OneCall plan it didn't show up as 'activated' in the OpenWeatherMap UI.
After telling them in their feedback section it took a few hours and now it's working.

**Comment by woheller69** [comment]
you should better use omWeather. Data is much better in my view.

**Comment by marcofeltmann** [comment]
Compared to the data from Deutscher Wetterdienst they are both similar and I love to use my own API key for getting the data.

I used omWeather quite a bit and was unhappy with the data quality.
Does it support open-meteo API key configuration as well?

**Comment by marcofeltmann** [comment]
I love API and use them a lot in personal projects.
So I'll switch to omWeather, duplicate the diagram widget and ask for open-meteo api key configuration.

Why do you still maintain radarWeather?

**Comment by woheller69** [comment]
many people are using it an in some regions data by OpenWeatherMap may be better. The apps are very similar, so maintaining is not a big thing.

But OpenWeatherMap is the opposite of "open".
And Open-Meteo is even open-source and works without API key.

**Comment by drewbitt** [comment]
FYI, you can see here which is best for you https://www.forecastadvisor.com/. May want to link to it in a README. For me, Openweather and Open-Meteo are close to each other but both pretty poor.
