### ISSUE TITLE
Feature Request: Radar time displayed in user or location timezone

### ISSUE THREAD

**Issue by drewbitt** [woheller69/weather#91]
Hello,

In the radar view I am getting the local time shown as GMT / UTC and not the timezone of the area I am viewing or even my device time. I would like this to not be UTC and several hours off for me. 

Screenshot in the USA: 
![share_775392993875981685](https://github.com/woheller69/weather/assets/26885897/d793af30-2c3f-462e-9b6b-673ca71e0be4)

**Comment by woheller69** [comment]
In radar view you are getting the time of the location you have set.
If you set New York as location you will see the time there and not your current time at home

**Comment by drewbitt** [comment]
That is not happening. The location on the radar is in the US; the time is GMT / Europe. 

I found the issue, the API call was not loading for the weather but the radar worked, but the local time  adjustment it is required that the main weather API call was successful.

**Comment by woheller69** [comment]
Yes, it gets the time zone difference from the weather API.
