### ISSUE TITLE
Sanitizing the user input of API key

### ISSUE THREAD

**Issue by Code7R** [woheller69/weather#93]
**How to Reproduce**
1. Go to OpenWeather API page
2. Doubleclick your API key
3. Share this via QR code (browser plugin) with your android
4. Scan and enter that key into the RadarWeather app

**Expected behavior**
Everything should work as normal.

**Observed behavior**
Error bubble, telling that it's unable to communicate.  Later investigation (logcat, and turning on/off the OneAPI3.0 checkbox) has revealed a HTTP401 error and the called URL. And only in that URL I could see what was wrong with it: the API key was transferred to Android with a prefix of some whitespace characters (from copy-pasting from their page, format characters in the table). Which went unnoticed all the way but eventually they were included in the URL with URL-encoding.

Proposal: please sanitize user input, trim leading/trailing whitespace.

**Environment (please complete the following information):**
 - App version: 6.4 (from F-Droid)
 - Android version: 14

**Comment by woheller69** [comment]
This app will no longer be updated due to the credit card requirement of OpenWeatherMap.
Please switch to Cirrus.
https://github.com/woheller69/omweather
